const fs = require('fs');

const problemsJson = JSON.parse(fs.readFileSync('src/data/problems.json', 'utf8'));

// Canonical title mapping to merge known duplicate variations into clean standard LeetCode titles
const canonicalMap = {
  "3 sum": "3Sum",
  "3sum": "3Sum",
  "4 sum": "4Sum",
  "4sum": "4Sum",
  "3sum smaller": "3Sum Smaller",
  "sort colors (dutch national flag)": "Sort Colors",
  "sort colors": "Sort Colors",
  "sort an array of 0's 1's and 2's": "Sort Colors",
  "kadane's algorithm": "Maximum Subarray (Kadane's Algorithm)",
  "maximum subarray (kadane)": "Maximum Subarray (Kadane's Algorithm)",
  "maximum subarray": "Maximum Subarray (Kadane's Algorithm)",
  "kadane's algorithm / maximum subarray": "Maximum Subarray (Kadane's Algorithm)",
  "inversion of array (merge sort)": "Inversion of Array",
  "inversion of array (pre-req: merge sort)": "Inversion of Array",
  "count inversions": "Inversion of Array",
  "two sum ii input array is sorted": "Two Sum II - Input Array Is Sorted",
  "two sum ii (sorted)": "Two Sum II - Input Array Is Sorted",
  "two sum ii – input array is sorted": "Two Sum II - Input Array Is Sorted",
  "find the repeating and missing number": "Find the Repeating and Missing Number",
  "find the missing and repeating number": "Find the Repeating and Missing Number",
  "implement atoi": "String to Integer (atoi)",
  "implement atoi/strstr": "String to Integer (atoi)",
  "string to integer (atoi)": "String to Integer (atoi)",
  "find the index (strstr)": "Find the Index of the First Occurrence in a String (strStr)",
  "find all numbers disappeared in an array": "Find All Numbers Disappeared in an Array",
  "find all numbers disappeared in array": "Find All Numbers Disappeared in an Array",
  "group words by anagrams": "Group Anagrams",
  "group anagrams": "Group Anagrams",
  "pascal's triangle": "Pascal's Triangle",
  "pascal's triangle i": "Pascal's Triangle",
  "maximum product subarray in an array": "Maximum Product Subarray",
  "maximum product subarray": "Maximum Product Subarray",
  "max product subarray": "Maximum Product Subarray",
  "trapping rainwater": "Trapping Rain Water",
  "trapping rain water": "Trapping Rain Water",
  "longest consecutive sequence in an array": "Longest Consecutive Sequence",
  "longest consecutive sequence": "Longest Consecutive Sequence",
  "majority element-i": "Majority Element",
  "majority element": "Majority Element",
  "majority element (boyer-moore)": "Majority Element",
  "majority element-ii": "Majority Element II",
  "majority element ii": "Majority Element II",
  "reverse every word in a string": "Reverse Words in a String",
  "reverse words in a string": "Reverse Words in a String",
  "rotate matrix by 90 degrees": "Rotate Image",
  "rotate image": "Rotate Image",
  "search in a 2d matrix": "Search a 2D Matrix",
  "search a 2d matrix": "Search a 2D Matrix",
  "search in rotated sorted array-i": "Search in Rotated Sorted Array",
  "search in rotated sorted array": "Search in Rotated Sorted Array",
  "sort an array (merge sort)": "Sort an Array",
  "sort an array": "Sort an Array",
  "spiral matrix": "Spiral Matrix",
  "print the matrix in spiral manner": "Spiral Matrix",
  "stock buy and sell": "Best Time to Buy and Sell Stock",
  "best time to buy and sell stock": "Best Time to Buy and Sell Stock",
  "kmp algorithm / lps array": "KMP Algorithm (Find Pattern in String)",
  "kmp algorithm or lps array": "KMP Algorithm (Find Pattern in String)",
  "min insertions to make palindrome": "Minimum Insertions to Make a String Palindrome",
  "minimum insertions to make string palindrome": "Minimum Insertions to Make a String Palindrome",
  "lowest common ancestor of bst": "Lowest Common Ancestor of a Binary Search Tree",
  "lca in bst": "Lowest Common Ancestor of a Binary Search Tree",
  "lowest common ancestor of a bst": "Lowest Common Ancestor of a Binary Search Tree",
  "lca of bst": "Lowest Common Ancestor of a Binary Search Tree",
  "lowest common ancestor of binary tree": "Lowest Common Ancestor of a Binary Tree",
  "lowest common ancestor of a binary tree": "Lowest Common Ancestor of a Binary Tree",
  "lca in bt": "Lowest Common Ancestor of a Binary Tree",
  "populating next right pointers": "Populating Next Right Pointers in Each Node",
  "populating next right pointers in each node": "Populating Next Right Pointers in Each Node",
  "find peak element": "Find Peak Element",
  "peak element": "Find Peak Element",
  "pow(x, n)": "Pow(x, n)",
  "pow(x n)": "Pow(x, n)",
  "word ladder i": "Word Ladder",
  "word ladder": "Word Ladder",
  "design lru cache": "LRU Cache",
  "lru cache": "LRU Cache",
  "design lfu cache": "LFU Cache",
  "lfu cache": "LFU Cache",
  "design hashmap": "Design HashMap",
  "design hashset": "Design HashSet",
  "balanced parenthesis": "Valid Parentheses",
  "valid parentheses": "Valid Parentheses",
  "balanced paranthesis": "Valid Parentheses",
  "reverse a ll": "Reverse Linked List",
  "reverse linked list": "Reverse Linked List",
  "detect a loop in ll": "Linked List Cycle",
  "linked list cycle": "Linked List Cycle",
  "find cycle start (floyd's extended)": "Linked List Cycle II",
  "find the starting point in ll": "Linked List Cycle II",
  "linked list cycle ii": "Linked List Cycle II",
  "find middle of linked list": "Middle of the Linked List",
  "middle of the linked list": "Middle of the Linked List",
  "remove nth node from the back of the ll": "Remove Nth Node From End of List",
  "remove nth node from end": "Remove Nth Node From End of List",
  "remove nth node from end of list": "Remove Nth Node From End of List",
  "merge two sorted lists": "Merge Two Sorted Lists",
  "add two numbers": "Add Two Numbers",
  "add two numbers as linkedlist": "Add Two Numbers",
  "find the intersection point of y ll": "Intersection of Two Linked Lists",
  "intersection of two linked lists": "Intersection of Two Linked Lists",
  "check if ll is palindrome or not": "Palindrome Linked List",
  "palindrome linked list": "Palindrome Linked List",
  "flattening of ll": "Flatten a Multilevel Doubly Linked List",
  "clone a ll with random and next pointer": "Copy List with Random Pointer",
  "copy list with random pointer": "Copy List with Random Pointer",
  "rotate a ll": "Rotate List",
  "rotate list": "Rotate List",
  "reverse ll in group of given size k": "Reverse Nodes in k-Group",
  "reverse nodes in k group": "Reverse Nodes in k-Group",
  "reverse nodes in k-group": "Reverse Nodes in k-Group",
  "delete node in a ll o(1)": "Delete Node in a Linked List",
  "delete node in a linked list o(1)": "Delete Node in a Linked List",
  "delete node in a linked list": "Delete Node in a Linked List",
  "n meetings in one room": "Meeting Rooms",
  "meeting rooms": "Meeting Rooms",
  "minimum number of platforms required": "Minimum Number of Platforms / Meeting Rooms II",
  "minimum number of platforms required for a railway": "Minimum Number of Platforms / Meeting Rooms II",
  "minimum number of platforms": "Minimum Number of Platforms / Meeting Rooms II",
  "meeting rooms ii": "Minimum Number of Platforms / Meeting Rooms II",
  "minimum number of platforms / meeting rooms ii": "Minimum Number of Platforms / Meeting Rooms II",
  "job sequencing problem": "Job Sequencing Problem",
  "fractional knapsack": "Fractional Knapsack",
  "minimum coins": "Coin Change",
  "coin change": "Coin Change",
  "subset sums": "Subset Sums",
  "subsets ii": "Subsets II",
  "combination sum": "Combination Sum",
  "combination sum ii": "Combination Sum II",
  "palindrome partitioning": "Palindrome Partitioning",
  "permutation sequence": "Permutation Sequence",
  "permutations of a string": "Permutations",
  "permutations": "Permutations",
  "n queen": "N-Queens",
  "n-queens": "N-Queens",
  "n queens ii": "N-Queens II",
  "n-queens ii": "N-Queens II",
  "sudoku solver": "Sudoku Solver",
  "m coloring problem": "M-Coloring Problem",
  "rat in a maze": "Rat in a Maze Problem",
  "word break (print all ways)": "Word Break II",
  "word break ii": "Word Break II",
  "the n-th root of an integer": "N-th Root of an Integer",
  "matrix median": "Matrix Median",
  "single element in sorted array": "Single Element in a Sorted Array",
  "median of 2 sorted arrays": "Median of Two Sorted Arrays",
  "median of two sorted arrays": "Median of Two Sorted Arrays",
  "kth element of 2 sorted arrays": "K-th Element of Two Sorted Arrays",
  "allocate minimum number of pages": "Allocate Minimum Number of Pages",
  "aggressive cows": "Aggressive Cows",
  "implement max heap": "Implement Max Heap",
  "k-th largest element in an array": "Kth Largest Element in an Array",
  "kth largest element in an array": "Kth Largest Element in an Array",
  "maximum sum combination": "Maximum Sum Combination",
  "find median from data stream": "Find Median from Data Stream",
  "merge k sorted arrays": "Merge K Sorted Arrays",
  "top k frequent elements": "Top K Frequent Elements",
  "implement stack using arrays": "Implement Stack using Array",
  "implement queue using arrays": "Implement Queue using Array",
  "implement stack using queue": "Implement Stack using Queues",
  "implement stack using queue (using single queue)": "Implement Stack using Queues",
  "implement queue using stack": "Implement Queue using Stacks",
  "next greater element": "Next Greater Element I",
  "next greater element i": "Next Greater Element I",
  "sort a stack": "Sort a Stack",
  "next smaller element": "Next Smaller Element",
  "largest rectangle in a histogram": "Largest Rectangle in Histogram",
  "largest rectangle in histogram": "Largest Rectangle in Histogram",
  "sliding window maximum": "Sliding Window Maximum",
  "implement min stack": "Min Stack",
  "min stack": "Min Stack",
  "rotten oranges": "Rotting Oranges",
  "rotting oranges": "Rotting Oranges",
  "stock span problem": "Online Stock Span",
  "online stock span": "Online Stock Span",
  "maximum of minimums for every window size": "Maximum of Minimums for Every Window Size",
  "celebrity problem": "The Celebrity Problem",
  "longest palindrome in a string": "Longest Palindromic Substring",
  "longest palindromic substring": "Longest Palindromic Substring",
  "longest common prefix": "Longest Common Prefix",
  "rabin karp algorithm": "Rabin-Karp Algorithm",
  "z function": "Z Algorithm",
  "valid anagram": "Valid Anagram",
  "count and say": "Count and Say",
  "compare version numbers": "Compare Version Numbers",
  "inorder traversal": "Binary Tree Inorder Traversal",
  "binary tree inorder traversal": "Binary Tree Inorder Traversal",
  "preorder traversal": "Binary Tree Preorder Traversal",
  "binary tree preorder traversal": "Binary Tree Preorder Traversal",
  "postorder traversal": "Binary Tree Postorder Traversal",
  "binary tree postorder traversal": "Binary Tree Postorder Traversal",
  "right/left view of bt": "Binary Tree Right Side View",
  "binary tree right side view": "Binary Tree Right Side View",
  "bottom view of bt": "Bottom View of Binary Tree",
  "top view of bt": "Top View of Binary Tree",
  "vertical order traversal": "Vertical Order Traversal of Binary Tree",
  "print root to leaf path in bt": "Root to Leaf Paths",
  "maximum width of bt": "Maximum Width of Binary Tree",
  "maximum width of binary tree": "Maximum Width of Binary Tree",
  "level order traversal": "Binary Tree Level Order Traversal",
  "binary tree level order traversal": "Binary Tree Level Order Traversal",
  "maximum depth in bt": "Maximum Depth of Binary Tree",
  "maximum depth of binary tree": "Maximum Depth of Binary Tree",
  "diameter of binary tree": "Diameter of Binary Tree",
  "check for balanced binary tree": "Balanced Binary Tree",
  "balanced binary tree": "Balanced Binary Tree",
  "check if two trees are identical or not": "Same Tree",
  "same tree": "Same Tree",
  "zig zag or spiral traversal": "Binary Tree Zigzag Level Order Traversal",
  "binary tree zigzag level order": "Binary Tree Zigzag Level Order Traversal",
  "boundary traversal": "Boundary Traversal of Binary Tree",
  "maximum path sum": "Binary Tree Maximum Path Sum",
  "binary tree maximum path sum": "Binary Tree Maximum Path Sum",
  "construct a bt from preorder and inorder": "Construct Binary Tree from Preorder and Inorder Traversal",
  "construct bt from preorder and inorder": "Construct Binary Tree from Preorder and Inorder Traversal",
  "construct a bt from postorder and inorder": "Construct Binary Tree from Inorder and Postorder Traversal",
  "construct bt from postorder and inorder": "Construct Binary Tree from Inorder and Postorder Traversal",
  "symmetric binary tree": "Symmetric Tree",
  "symmetric tree": "Symmetric Tree",
  "flatten binary tree to linked list": "Flatten Binary Tree to Linked List",
  "children sum property in binary tree": "Children Sum Property",
  "children sum property": "Children Sum Property",
  "search in bst": "Search in a Binary Search Tree",
  "construct bst from given keys": "Convert Sorted Array to Binary Search Tree",
  "construct a bst from a preorder traversal": "Construct Binary Search Tree from Preorder Traversal",
  "check if a tree is a bst or not": "Validate Binary Search Tree",
  "validate binary search tree": "Validate Binary Search Tree",
  "inorder successor and predecessor in bst": "Inorder Successor in BST",
  "floor in a bst": "Floor in BST",
  "ceil in a bst": "Ceil in BST",
  "find k-th smallest element in bst": "Kth Smallest Element in a BST",
  "kth smallest element in a bst": "Kth Smallest Element in a BST",
  "kth smallest and largest element in bst": "Kth Smallest Element in a BST",
  "two sum in bst": "Two Sum IV - Input is a BST",
  "bst iterator": "BST Iterator",
  "size of the largest bst in a binary tree": "Largest BST in Binary Tree",
  "serialize and de-serialize bt": "Serialize and Deserialize Binary Tree",
  "serialize and deserialize binary tree": "Serialize and Deserialize Binary Tree",
  "binary tree to doubly linked list": "Binary Tree to DLL",
  "kth largest element in a stream of running integers": "Kth Largest Element in a Stream",
  "kth largest element in a stream": "Kth Largest Element in a Stream",
  "flood-fill algorithm": "Flood Fill",
  "clone graph": "Clone Graph",
  "detect a cycle in undirected graph using bfs": "Course Schedule / Detect Cycle in Undirected Graph",
  "detect a cycle in undirected graph using dfs": "Course Schedule / Detect Cycle in Undirected Graph",
  "detect a cycle in a directed graph using dfs": "Detect Cycle in Directed Graph",
  "detect a cycle in a directed graph using bfs": "Detect Cycle in Directed Graph",
  "topological sort bfs": "Topological Sort",
  "topological sort dfs": "Topological Sort",
  "number of islands(do in grid and graph both)": "Number of Islands",
  "number of islands": "Number of Islands",
  "bipartite graph": "Is Graph Bipartite?",
  "bipartite check using dfs": "Is Graph Bipartite?",
  "strongly connected component(using kosaraju’s algo)": "Strongly Connected Components (Kosaraju's Algorithm)",
  "strongly connected components (kosaraju's algo)": "Strongly Connected Components (Kosaraju's Algorithm)",
  "dijkstra's algorithm": "Dijkstra's Algorithm",
  "dijkstra algorithm": "Dijkstra's Algorithm",
  "bellman ford algorithm": "Bellman-Ford Algorithm",
  "floyd warshall algorithm": "Floyd-Warshall Algorithm",
  "mst using prim's algo": "Prim's Algorithm for Minimum Spanning Tree",
  "mst using kruskal’s algo": "Kruskal's Algorithm for Minimum Spanning Tree",
  "longest increasing subsequence": "Longest Increasing Subsequence",
  "longest common subsequence": "Longest Common Subsequence",
  "0 and 1 knapsack": "0/1 Knapsack",
  "0/1 knapsack": "0/1 Knapsack",
  "edit distance": "Edit Distance",
  "maximum sum increasing subsequence": "Maximum Sum Increasing Subsequence",
  "matrix chain multiplication": "Matrix Chain Multiplication",
  "minimum sum path in the matrix, (count paths and similar type do, also backtrack to find the minimum path)": "Minimum Path Sum",
  "minimum path sum": "Minimum Path Sum",
  "coin change ii": "Coin Change II",
  "subset sum equals to target": "Subset Sum Problem",
  "subset sum equals target": "Subset Sum Problem",
  "rod cutting problem": "Rod Cutting Problem",
  "super egg drop": "Super Egg Drop",
  "word break": "Word Break",
  "palindrome partitioning (mcm variation)": "Palindrome Partitioning II (MCM)",
  "maximum profit in job scheduling": "Maximum Profit in Job Scheduling",
  "trie implementation and operations": "Implement Trie (Prefix Tree)",
  "trie implementation and advanced operations": "Implement Trie II (Prefix Tree)",
  "longest word with all prefixes": "Complete String / Longest Word with All Prefixes",
  "number of distinct substrings in a string": "Number of Distinct Substrings in a String",
  "power set (this is very important)": "Power Set",
  "power set": "Power Set",
  "maximum xor of two numbers in an array": "Maximum XOR of Two Numbers in an Array",
  "maximum xor with an element from an array": "Maximum XOR With an Element From Array"
};

function getNormKey(str) {
  let s = str.toLowerCase().trim();
  if (canonicalMap[s]) {
    s = canonicalMap[s].toLowerCase().trim();
  }
  return s
    .replace(/\(.*?\)/g, '')
    .replace(/[^a-z0-9]/g, '');
}

// Build existing map of normalized titles in problems.json
const existingMap = new Map();
problemsJson.forEach(p => {
  const normKey = getNormKey(p.title);
  existingMap.set(normKey, p);
});

// Read DSA_Tracker.csv
const fileContent = fs.readFileSync('/home/mdasif/Documents/production_rag/DSA_Tracker.csv', 'utf8');
const lines = fileContent.split('\n').filter(l => l.trim().length > 0);

// Skip header
const header = lines[0];
let addedCount = 0;
const missingFound = [];

for (let i = 1; i < lines.length; i++) {
  const line = lines[i];
  const parts = line.split(',');
  if (parts.length < 3) continue;
  
  const rawTopic = parts[1] ? parts[1].replace(/^"|"$/g, '').trim() : 'General';
  const rawTitle = parts[2] ? parts[2].replace(/^"|"$/g, '').trim() : '';
  const rawDiff = parts[3] ? parts[3].replace(/^"|"$/g, '').trim() : 'Medium';
  
  if (!rawTitle) continue;
  
  const normKey = getNormKey(rawTitle);
  
  if (!existingMap.has(normKey)) {
    const canonicalTitle = canonicalMap[rawTitle.toLowerCase().trim()] || rawTitle;
    const newProb = {
      id: problemsJson.length + 1,
      title: canonicalTitle,
      slug: canonicalTitle.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
      url: `https://leetcode.com/problemset/all/?search=${encodeURIComponent(canonicalTitle)}`,
      topic: rawTopic || 'General',
      difficulty: rawDiff || 'Medium',
      priority: 'P2',
      pattern: '',
      companies: ['Amazon', 'Google'],
      mlBoost: false,
      notes: 'Imported from DSA_Tracker.csv'
    };
    
    existingMap.set(normKey, newProb);
    problemsJson.push(newProb);
    missingFound.push(canonicalTitle);
    addedCount++;
  }
}

console.log(`DSA_Tracker.csv Analysis Complete:`);
console.log(`- Missing problems found and added: ${addedCount}`);
if (addedCount > 0) {
  console.log(`- New Problems Added:`, missingFound);
}

// Re-write problems.json
fs.writeFileSync('src/data/problems.json', JSON.stringify(problemsJson, null, 2), 'utf8');
